Portal medical atention order
cormaza/transmedical_proceso_base pull request #7
Opened 2022-01-07 05:53 UTC by nelio2120

2022-01-07 12:37 UTC, cormaza requested changes
Por favor revisa los comentarios

2022-01-07 12:37 UTC, cormaza commented on models/medical_attention_order.py
> +        "l10n_ec.common.document.electronic"
Este no es un documento electrónico, ni uno suceptible de campañas de marketing, no creo que sea necesario agregar estos mixins

2022-01-07 12:37 UTC, cormaza commented on __manifest__.py
> +        "utm",
No es necesario agregar esta dependencia, este módulo te agrega información de marketing al objecto, como medio, campaña, fuente

2022-01-07 12:37 UTC, cormaza commented on controllers/transmedical_portal_order_atencion.py
> +    @http.route(['/my/atencion_order', '/my/atencion_order/page/<int:page>'], type='http', auth="user", website=True)
atention_order

2022-01-07 12:37 UTC, cormaza commented on controllers/transmedical_portal_order_atencion.py
> +        ["/my/atencion_order/<int:medical_order_id>"],
atention_order

2022-01-07 12:37 UTC, cormaza commented on controllers/transmedical_portal_order_atencion.py
> +        # values = self._delivery_note_get_page_view_values(medical_order_obj, access_token, **kw)
borrar codigo comentado si no se usa

2022-01-07 12:37 UTC, cormaza commented on models/medical_attention_order.py
> +            order_id.access_url = "/my/atencion_order/%s" % (order_id.id)
atention_order

2022-01-07 12:37 UTC, cormaza commented on security/groups.xml
> +            <field name="domain_force">[('message_partner_ids','child_of',[user.commercial_partner_id.id])]</field>
No he visto en alguna parte del código que tengas como seguidor a nadie, me aprece que esta regla no va a funcionar, deberías usar el campo del partner y el beneficiario para hacer este dominio, no debería estar el comercial, eso es cuando es un pedido de venta

2022-01-07 12:37 UTC, cormaza commented on security/ir.model.access.csv
> +"access_model_medical_portal_publico","access_model_medical_portal_publico","model_medical_attention_order","base.group_portal",1,0,0,0
Ingles, public

2022-01-07 12:37 UTC, cormaza commented on views/portal_medical_atention_order_template.xml
> +                                        <a href="#electronic_chatter" class="small">
Debe implementarse el chater original de odoo, no el de deocumentos electrónicos

2022-01-12 20:38 UTC, cormaza requested changes

2022-01-12 20:38 UTC, cormaza commented on controllers/transmedical_portal_order_atencion.py
> +        partner = request.env.user.partner_id.id
En teoría con la regla de registro implementada, este dominio de aqui es innecesario

2022-01-12 20:48 UTC, nelio2120 commented on controllers/transmedical_portal_order_atencion.py
> +        partner = request.env.user.partner_id.id
Le comento que ese dominio lo agregue para mostrar cuantos documentos de ODA existes, es el contador de las ODA, si no se coloca el dominio, mostraria la cantidad de todas las oda pero cuando ingrese al menú solo va a haber las del usuario, consulto, debería reemplazarse o quedarse así ?

2022-01-13 12:14 UTC, cormaza requested changes
Solo cambia el nombre del archivo, y cerramos el pr para poder probarlo

2022-01-13 12:14 UTC, cormaza commented on controllers/__init__.py
> +from . import transmedical_portal_order_atencion
transmedical_portal_order_atention

2022-01-15 14:25 UTC, cormaza approved these changes
Revisión funcional ok

2022-01-15 14:25 UTC, merged